fix asset managers ops
balancer-labs/balancer-subgraph-v2 pull request #219
Opened 2022-06-17 18:57 UTC by mendesfabio

2022-06-20 15:09 UTC, markusbkoch commented on schema.graphql
> +  managed: BigDecimal!
`managedBalance` and `cashBalance` are more intuitive IMO

2022-06-20 15:59 UTC, markusbkoch commented on schema.graphql
> +  Report
For consistency with the solidity code, let's go with `Update` instead? https://github.com/balancer-labs/balancer-v2-monorepo/blob/d2794ef7d8f6d321cde36b7c536e8d51971688bd/pkg/interfaces/contracts/vault/IVault.sol#L717

2022-06-20 16:05 UTC, markusbkoch commented on schema.graphql
> +  managed: BigDecimal!
For clarity, `cashBalance` would have to be added as a new attribute. While it could be computed from `balance - managedBalance`, we need to make it explicit to allow for filtering in queries

2022-06-20 16:07 UTC, markusbkoch commented on src/mappings/vault.ts
> +    management.type = 'Deposit';
Shouldn't this be reading from the enum?

2022-06-20 16:10 UTC, markusbkoch commented on src/mappings/vault.ts
> +  management.assetManagerAddress = assetManagerAddress;
With the asset manager becoming an attribute of `poolToken` maybe do we need this?

2022-06-20 16:13 UTC, markusbkoch commented on schema.graphql
> +  managedAmount: BigDecimal!
Now that I think about it `cashDelta` and `managedDelta` would be more clear I think

2022-06-20 16:24 UTC, markusbkoch requested changes
Suggesting a few minor changes, mostly attribute naming

2022-06-20 18:12 UTC, mendesfabio commented on src/mappings/vault.ts
> +    management.type = 'Deposit';
yeah, I thought about it when coding, but it seems `enums` are not automatically generated from the schema. Looking at the handler for joining you will see we did it in the same way: `join.type = 'Join'`

2022-06-21 16:04 UTC, markusbkoch approved these changes

2022-06-24 13:47 UTC, merged