Subgraphs for primary issue and secondary issue pools
balancer-labs/balancer-subgraph-v2 pull request #244
Opened 2022-08-11 16:24 UTC by kallolborah

@mendesfabio @markusbkoch 
I am creating this PR for two new custom pools that we have implemented. I was asked by @johngrantuk to mark the subgraph changes for review by you.

2022-08-11 17:15 UTC, markusbkoch commented
Thanks, we'll review as soon as possible. In the meantime, have you
deployed the resulting subgraph to the hosted service so we can have a
look at it? If not, you doing it would accelerate the process. Thanks!

On Thu, Aug 11, 2022, 17:25 Kallol Borah ***@***.***> wrote:

> @mendesfabio <https://github.com/mendesfabio> @markusbkoch
> <https://github.com/markusbkoch>
> I am creating this PR for two new custom pools that we have implemented. I
> was asked by @johngrantuk <https://github.com/johngrantuk> to mark the
> subgraph changes for review by you.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/balancer-labs/balancer-subgraph-v2/pull/244
> Commit Summary
>
>    - cd12106
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/commits/cd121064194a53a4c55a6a2f3bfd95a79645de1f>
>    added primary issue pool
>    - 8d21ba3
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/commits/8d21ba33de21ed79e1b138651eea21ff83c0e02a>
>    added secondary issue pool
>    - 6db461d
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/commits/6db461d5178ce5ca328471dbdd73453a21d3d809>
>    added pool events and controllers for primary and secondary pools
>    - 30de7db
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/commits/30de7dbda670c005d9fecd1e792c774c90107598>
>    fixed pool controllers
>    - 5f79ca2
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/commits/5f79ca28bc4f82e2064c19705ede4e17370dad10>
>    deployed to rinkeby
>
> File Changes
>
> (20 files
> <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files>)
>
>    - *A* abis/PrimaryIssuePool.json
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-f1a08a9ca5730c2eb3080345dcf16803b7d6973e03d1bceb092d7d5308e47a8e>
>    (1066)
>    - *A* abis/PrimaryIssuePoolFactory.json
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-3efd9ed1e87fabe8f19979ea64948bee1e2f0fa49e748694cdee1fdf3b2e1af3>
>    (223)
>    - *A* abis/SecondaryIssuePool.json
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-07ad3c5cce6c2f61075a83bad34e01540b830ce236c0209590acfb71f4584064>
>    (1210)
>    - *A* abis/SecondaryIssuePoolFactory.json
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-d01e8733c53c73e4117888f22742c978bffa4cbaf64a7e6fe748dbef614fc3f1>
>    (218)
>    - *M* networks.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-5747e985ae97ccd888b751ddf61c3d147d514a33ded9ec173f6abbb8100cc216>
>    (21)
>    - *M* schema.graphql
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-efc1675187620595b0844197a25c35eac9b6df752f9182e5cffddee6f27a8489>
>    (39)
>    - *M* scripts/update-abis.ts
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-2a59c9acffbd2a2b3f60fbaa185b836f01af0b3226c66f3ff8bb3f7b5aa31083>
>    (1)
>    - *M* src/mappings/helpers/misc.ts
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-e135cd4cddfaa4828392be9384dc23947ffcff77e16ac1c697927740f85c3dea>
>    (11)
>    - *M* src/mappings/helpers/pools.ts
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-f8a7982cd6253f137a0334c68fd9871fbb527dbbaa0b5111984867e46524f3a3>
>    (2)
>    - *M* src/mappings/poolController.ts
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-0a0615bb9669b036e50f28606813d1bf939977360cd4b8b09ebefba841bbc8ea>
>    (83)
>    - *M* src/mappings/poolFactory.ts
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-2a6e7f04b0db5f954610396003c139fa618199f4833fe3b6b809a217c843573d>
>    (90)
>    - *M* subgraph.arbitrum.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-ce7db8ca9db9651388cd506036ebf3cbd7af1995c829fb955280d1e87bad44d9>
>    (110)
>    - *M* subgraph.goerli.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-0934cc07e665426075a3085b5fb8f224754b7a0fbc0ac9945a2ff8a6ed6ebe6a>
>    (108)
>    - *M* subgraph.kovan.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-64ce12f8d0862ab3e7bfddecc12828237b85270ca7c9cc7bb5081fd9c0056860>
>    (108)
>    - *M* subgraph.polygon.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-4380e2ca7ca8c42cd3ed58805d865ce8c2e87128a4ab07a95e1f6204f5b24e4f>
>    (108)
>    - *M* subgraph.polygonGrafted.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-88c125c161d61bb525a2aa1f707d7b5f0f7087b79832ab0f0cc9e3de19cf4235>
>    (108)
>    - *M* subgraph.rinkeby.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-469bb5f9ed0231d105422f1f4c3315024f42199c4153c46a5c23190ea8996ec7>
>    (108)
>    - *M* subgraph.ropsten.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-decf19d93051cc3876de00ac385a8811f5fd1264cd04815b927e0e75929d4819>
>    (108)
>    - *M* subgraph.template.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-a48e48a516f889d4658471a699026ee67408b7a3c4b73090ac053d472930c8fb>
>    (108)
>    - *M* subgraph.yaml
>    <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244/files#diff-a725ae1c058279c10ca4753a5d7090b61659b60bd36fa43d75861fabffa7d367>
>    (108)
>
> Patch Links:
>
>    - https://github.com/balancer-labs/balancer-subgraph-v2/pull/244.patch
>    - https://github.com/balancer-labs/balancer-subgraph-v2/pull/244.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/balancer-labs/balancer-subgraph-v2/pull/244>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIKABI6D77NB2B7B6AHFFR3VYUSOJANCNFSM56IZJVUA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-11 18:43 UTC, kallolborah commented
> Thanks, we'll review as soon as possible. In the meantime, have you deployed the resulting subgraph to the hosted service so we can have a look at it? If not, you doing it would accelerate the process. Thanks!
> […](#)

@markusbkoch 
Yes, the subgraph is deployed on the hosted service https://thegraph.com/hosted-service/subgraph/verified-network/balancer

2022-08-12 11:00 UTC, mendesfabio requested changes
hey, @kallolborah, thanks for this! I reviewed your code and requested some changes. I'm also changing the base branch to `dev`. Please pull the latest changes and fix the conflicts. Feel free to ask any questions 😃

2022-08-12 12:00 UTC, merged

2022-08-13 06:55 UTC, kallolborah commented on schema.graphql
> +  poolId: Pool!
Changed it to 'pool', but I see poolId everywhere else, hope it won't break anything now

2022-08-13 09:19 UTC, kallolborah commented on schema.graphql
> +  counterparty: Bytes!
Referring to User now for both investor and counterparty

2022-08-13 09:24 UTC, kallolborah commented on schema.graphql
> +  status: Bytes!
I checked this and status is 'pending' or 'settled', so using Bytes here

2022-08-13 14:40 UTC, kallolborah commented on src/mappings/helpers/misc.ts
> +
I checked this again. The Primary and Secondary Issue pools are 2 token pools (1 security + 1 cash token). No BPT is mined for pool joins or pre-mined also. As I understand, `PoolToken` in this case is the poolId-securityAddress which is returned by `getPoolTokenId()` and what `loadPrimarySubscriptions()` and `loadSecondaryTrades()` are doing is using the same PoolToken ID to load subscriptions collected in Primary issue pools and load trades generated in Secondary issue pools. `PrimaryIssues` and `SecondaryTrades` are defined in the schema. Is there anything wrong with this ?

2022-08-13 15:00 UTC, kallolborah commented on schema.graphql
> +  assetName: String!
`assetIn`, `security`, `currency` are now referencing `Token`

2022-08-13 15:01 UTC, kallolborah commented on schema.graphql
> +  currency: Bytes!
`party`, `counterparty` are now referencing `User`