GyroCEMM -> GyroE + factory address update
balancer-labs/balancer-subgraph-v2 pull request #272
Opened 2022-09-29 13:47 UTC by joshguha

2022-09-29 13:53 UTC, mendesfabio requested changes

2022-09-29 13:53 UTC, mendesfabio commented on networks.yaml
>      startBlock: 7546831
```suggestion
    startBlock: 7668885
```

2022-09-29 13:54 UTC, joshguha commented
Contracts / ABIs need to be updated with new nomenclature - closing PR for now.

2022-11-11 13:49 UTC, joshguha commented
@markusbkoch @mendesfabio Changes have been updates - PR is ready for review!

2022-11-11 17:36 UTC, markusbkoch approved these changes

2022-11-14 17:16 UTC, mendesfabio approved these changes

2022-11-14 17:20 UTC, merged