FXPool custom logic for swap fee calculation
balancer-labs/balancer-subgraph-v2 pull request #291
Opened 2022-10-20 02:05 UTC by schystz

At the moment, `Pool.totalSwapFee` for XaveFinance FXPools is displaying 0 on https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-polygon-v2-beta.

This PR adds the necessary adjustment in the swap fee calculation for XaveFinance FXPools.

For an example result, please refer to this deployment on our subgraph clone - https://thegraph.com/hosted-service/subgraph/xave-finance/balancer-v2-polygon

```
        "totalLiquidity": "1185044.562397210060690128760581697",
        "totalSwapVolume": "1535691.700875",
        "totalSwapFee": "1345.53874049492095".
        "swapsCount": "412"
```

2022-10-21 16:02 UTC, mendesfabio commented on src/mappings/vault.ts
> +      let rateRes = assimilator.try_getRate();
It seems the Assimilator doesn't emit events, but maybe there's an event the FXPool emits that we could use to store/update a cached rate value. What do you think @schystz? Ideally, this event should be less frequent than trades, so we avoid making some calls, but the cached rate should be sufficiently accurate.

2022-10-22 02:48 UTC, schystz commented on src/mappings/vault.ts
> +      let assimilatorRes = pool.try_assimilator(isTokenInBase ? tokenInAddress : tokenOutAddress);
Hi @markusbkoch , thanks for the valuable feedback!

> It's good practice to avoid calls when possible, especially on handlers that are expected to be very frequently processed

This is well noted, and we'll strive to practice this from now on (even on our own subgraphs). This makes perfect sense to me!

In this particular case, yes we can store the assimilator address upon emitting the `AssimilatorIncluded` event. I was thinking of simply adding a new property on the `Pool` entity. Thoughts?

```
type Pool @entity {
  ...
  # FXPool Only
  baseAssimilator: Bytes
  ...
}
```

2022-10-22 03:01 UTC, schystz commented on src/mappings/vault.ts
> +      let rateRes = assimilator.try_getRate();
Hi @markusbkoch, @mendesfabio, actually the assimilator simply calls a Chainlink price feed oracle:

```
    function getRate() public view override returns (uint256) {
        (, int256 price, , , ) = oracle.latestRoundData();
        return uint256(price);
    }
```

In our XSGD:USDC pool it'll be https://polygonscan.com/address/0x8CE3cAc0E6635ce04783709ca3CC4F5fc5304299#code.

There seem to be a `AnswerUpdated` event emitted whenever the rate changes. So I am thinking a solution could be to create a `PriceFeedOracle` entity and cache the latest rate there for each token. Do you guys think that will be sufficient?

2022-10-24 13:03 UTC, schystz commented on src/mappings/vault.ts
> +      let assimilatorRes = pool.try_assimilator(isTokenInBase ? tokenInAddress : tokenOutAddress);
New update! There is no need anymore to call `FXPool.assimilator()` on every swap as the assimilator address is now stored in `pool.baseAssimilator`. Let me know what you think of this solution @markusbkoch

2022-10-24 13:04 UTC, mendesfabio commented on src/mappings/vault.ts
> +      let assimilatorRes = pool.try_assimilator(isTokenInBase ? tokenInAddress : tokenOutAddress);
IIUC each asset has its assimilator, right? Then you should add this property to `PoolToken` entity.

2022-10-24 13:08 UTC, schystz commented on src/mappings/vault.ts
> +      let assimilatorRes = pool.try_assimilator(isTokenInBase ? tokenInAddress : tokenOutAddress);
That's correct @mendesfabio! Sure let me move it to `PoolToken`

2022-10-24 14:05 UTC, schystz commented on src/mappings/vault.ts
> +      let assimilatorRes = pool.try_assimilator(isTokenInBase ? tokenInAddress : tokenOutAddress);
We've moved the `assimilator` prop to `PoolToken` @mendesfabio

2022-10-25 13:26 UTC, mendesfabio requested changes

2022-10-25 13:26 UTC, mendesfabio commented on src/mappings/poolController.ts
> +export function handleAssimilatorIncluded(event: ethereum.Event): void {
```suggestion
export function handleAssimilatorIncluded(event: AssimilatorIncluded): void {
```

Running `yarn codegen` generates the typings for all events, then you can access the assimilator with `event.params.assimilator`.

2022-10-25 13:42 UTC, markusbkoch commented on src/mappings/vault.ts
> +      let rateRes = assimilator.try_getRate();
I might be overlooking something, but it seems to me `AnswerUpdated` is not emitted by the `assimilator.oracle` (ie, [0x8ce3](https://polygonscan.com/address/0x8CE3cAc0E6635ce04783709ca3CC4F5fc5304299#events)), but rather by the `assimilator.oracle.aggregator` (ie, [0x45ed](https://polygonscan.com/address/0x45ede0ea5cbbe380c663c7c3015cc7c986669fec#events) in this case). 

And the `oracle.aggregator` is mutable, so you'd have to keep track of changes to it too. The same applies to any link in this chain of dependencies.

2022-10-25 13:47 UTC, markusbkoch commented on src/mappings/helpers/constants.ts
> +let usdcAddressByNetwork: AddressByNetwork = {
@mendesfabio can we reuse some of what you implemented in `assets` so as to avoid new deployment IDs every time this is updated for new networks?

2022-10-25 14:48 UTC, markusbkoch commented on src/mappings/vault.ts
> +      let rateRes = assimilator.try_getRate();
Fabio and I just talked about the alternatives here and we feel like they might all be adding too much complexity too soon. For now let's leave the `getRate` there and we can optimize later if needed.

2022-10-26 02:24 UTC, schystz commented on src/mappings/poolController.ts
> +export function handleAssimilatorIncluded(event: ethereum.Event): void {
Updated on [2152b9](https://github.com/balancer-labs/balancer-subgraph-v2/pull/291/commits/2152b96f9618837ec56dae15aba2f2ee44efd52f) @mendesfabio  ^^

2022-10-27 12:29 UTC, mendesfabio commented on src/mappings/helpers/constants.ts
> +let usdcAddressByNetwork: AddressByNetwork = {
added stables to `assets.ts` in #294 -- we can merge this and I will fix the imports / remove the contants.

2022-10-27 13:32 UTC, mendesfabio approved these changes

2022-10-28 14:05 UTC, merged