Updated events for erc4626 linear pool factory
balancer-labs/balancer-subgraph-v2 pull request #359
Opened 2023-01-30 17:41 UTC by baileyspraggins

# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas

### `dev` -> `master`
- [ ] I have checked that all beta deployments have synced
- [ ] I have checked that the earliest block in the polygon pruned deployment is <insert block number>, <insert block date/time>
  - [ ] The earliest block is more than 24 hours old
- [ ] I have checked that core metrics are the same in the beta and production deployments

### Merges to `dev`
- [ ] I have checked that the graft base is not a pruned deployment

2023-01-30 17:49 UTC, baileyspraggins commented
Events within the ERC4626 Linear Pool Factory: 
```
    // This event allows off-chain tools to differentiate between different protocols that use this factory
    // to deploy Erc4626 Linear Pools.
    event Erc4626LinearPoolCreated(address indexed pool, uint256 indexed protocolId);

    // Record protocol ID registrations.
    event Erc4626LinearPoolProtocolIdRegistered(uint256 indexed protocolId, string name);

2023-02-01 17:18 UTC, markusbkoch commented on src/mappings/poolFactory.ts
> +  handleNewLinearPool(poolCreatedEvent, PoolType.ERC4626Linear, 1, event.params.protocolId.toI32());
pooltype version here should be 3
```suggestion
  handleNewLinearPool(poolCreatedEvent, PoolType.ERC4626Linear, 3, event.params.protocolId.toI32());
```

2023-02-01 17:36 UTC, markusbkoch commented on manifest.template.yaml
> +        - name: ERC4626LinearPoolV3Factory
I think you meant `ERC4626LinearPoolV3Pool` but also I'm not sure this is needed, is it @mendesfabio ?

2023-02-01 17:37 UTC, markusbkoch commented on src/mappings/poolFactory.ts
> +// TODO: Import Erc4626LinearPoolCreated once abi is addded
Keep in mind that for this we don't need the complete and finalized ABI, just a mock ABI file with the Erc4626LinearPoolCreated event

2023-02-01 22:20 UTC, baileyspraggins commented
Missing startBlocks and Goerli Address

2023-02-02 09:21 UTC, markusbkoch requested changes
Thank you. Another couple of change requests:
- add the `.json` extension to file `ERC4626LinearPoolV3Factory`
- set the PR target to `staging-dev` instead of `master`
- set `startBlock` to the most recent block on each network
- fix lint errors (`yarn lint --fix`)

The Goerli address is not really a blocker for this -  we can merge that in later with no impact to the sync process of the production networks

2023-02-02 09:21 UTC, markusbkoch commented on manifest.template.yaml
> +          file: ./abis/ERC4626LinearPoolV3Pool.json
```suggestion
          file: ./abis/ERC4626LinearPoolV3.json
```

2023-02-03 17:22 UTC, markusbkoch requested changes

2023-02-03 17:22 UTC, markusbkoch commented on networks.yaml
> +    startBlock: 71912978
```suggestion
    startBlock: 57735268
```

2023-02-03 17:22 UTC, markusbkoch commented on networks.yaml
> +    startBlock: 71912978
source: https://arbiscan.io/

2023-02-03 17:43 UTC, merged